/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.util.ArrayList;

/**
 *
 * @author Loredana
 */
public class GUIPatrulater extends javax.swing.JFrame {

    /**
     * Creates new form GUIPatrulater
     */
    public GUIPatrulater() {
        initComponents();
    }
    String mesajLatura1, mesajLatura2, mesajLatura3, mesajLatura4;
    Patrulater patrulater = new Patrulater();
    double latura1, latura2, latura3, latura4;
    ArrayList<Patrulater> vectPatr = new ArrayList<Patrulater>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        latura1Ecran = new javax.swing.JTextField();
        latura2Ecran = new javax.swing.JTextField();
        latura3Ecran = new javax.swing.JTextField();
        latura4Ecran = new javax.swing.JTextField();
        butonPerimetru = new javax.swing.JButton();
        ecranPerimetru = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ecranAfisareTot = new javax.swing.JTextArea();
        vectorLista = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patrulater");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 58, 309, 69));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel2.setText("Latura 1");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 193, 114, 36));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Latura 4");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 410, 114, 36));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel4.setText("Latura 2");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 264, 114, 36));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel5.setText("Latura 3");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 339, 114, 36));

        latura1Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura1Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura1EcranFocusLost(evt);
            }
        });
        getContentPane().add(latura1Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 193, 160, 36));

        latura2Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura2Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura2EcranFocusLost(evt);
            }
        });
        getContentPane().add(latura2Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 268, 160, 36));

        latura3Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura3Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura3EcranFocusLost(evt);
            }
        });
        getContentPane().add(latura3Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 339, 160, 36));

        latura4Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura4Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura4EcranFocusLost(evt);
            }
        });
        getContentPane().add(latura4Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 414, 160, 36));

        butonPerimetru.setBackground(new java.awt.Color(204, 0, 0));
        butonPerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonPerimetru.setText("Perimetru");
        butonPerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonPerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 214, 145, 50));

        ecranPerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        getContentPane().add(ecranPerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 180, 40));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel7.setText("Exemple patrulatere :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        ecranAfisareTot.setColumns(20);
        ecranAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisareTot.setRows(5);
        jScrollPane1.setViewportView(ecranAfisareTot);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 350, 100));

        vectorLista.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        vectorLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------", "Patrulater 1", "Patrulater 2", "Patrulater 3", "Patrulater 4" }));
        vectorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorListaActionPerformed(evt);
            }
        });
        getContentPane().add(vectorLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 180, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Loredana\\Desktop\\Test\\src\\Test\\resursePoze\\generic.jpg")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonPerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPerimetruActionPerformed
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();
        mesajLatura2 = latura2Ecran.getText();
        mesajLatura3 = latura3Ecran.getText();
        mesajLatura4 = latura4Ecran.getText();

        try {                                             //se verifica daca sunt numere sau alte caractere
            latura1 = Double.parseDouble(mesajLatura1);
            latura2 = Double.parseDouble(mesajLatura2);
            latura3 = Double.parseDouble(mesajLatura3);
            latura4 = Double.parseDouble(mesajLatura4);

            if (latura1 > 0 && latura2 > 0 && latura3 > 0 && latura4 > 0) {

                patrulater.setLatura1(latura1);
                patrulater.setLatura2(latura2);
                patrulater.setLatura3(latura3);
                patrulater.setLatura4(latura4);

                double perim = patrulater.calculPerimetru();

                System.out.println("Perimetrul este " + perim);
                ecranPerimetru.setText(Double.toString(perim));
            }
        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranPerimetru.setText("EROARE!Dim incorecte");
            System.out.println("EROARE!dimensiuni incorecte");
        }

    }//GEN-LAST:event_butonPerimetruActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GUImain meniu = new GUImain();  //aici cand se inchide fereasra,sa se deschida meniul initial
        meniu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void latura1EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura1EcranFocusLost
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();
        try {
            latura1 = Double.parseDouble(mesajLatura1);
            if (latura1 < 0) {
                latura1Ecran.setText("EROARE!Negativ");
                System.out.println("EROARE! Negativ");
            }
            if (latura1 > 100) {  //sa fie mai mic decat 100

                latura1Ecran.setText("EROARE!Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura1.isEmpty()) {
                latura1Ecran.setText("");
            } else {
                latura1Ecran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }
    }//GEN-LAST:event_latura1EcranFocusLost

    private void latura2EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura2EcranFocusLost
        // TODO add your handling code here:
        mesajLatura2 = latura2Ecran.getText();
        try {
            latura2 = Double.parseDouble(mesajLatura2);
            if (latura2 < 0) {
                latura2Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");
            }
            if (latura2 > 100) {  //sa fie mai mic decat 100

                latura2Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura2.isEmpty()) {
                latura2Ecran.setText("");
            } else {
                latura2Ecran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }
    }//GEN-LAST:event_latura2EcranFocusLost

    private void latura3EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura3EcranFocusLost
        // TODO add your handling code here:
        mesajLatura3 = latura3Ecran.getText();
        try {
            latura3 = Double.parseDouble(mesajLatura3);
            if (latura3 < 0) {
                latura3Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE!negativ");
            }
            if (latura3 > 100) {  //sa fie mai mic decat 100

                latura3Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura3.isEmpty()) {
                latura3Ecran.setText("");
            } else {
                latura3Ecran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }
    }//GEN-LAST:event_latura3EcranFocusLost

    private void latura4EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura4EcranFocusLost
        // TODO add your handling code here:
        mesajLatura4 = latura4Ecran.getText();
        try {
            latura4 = Double.parseDouble(mesajLatura4);
            if (latura4 < 0) {
                latura4Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE!Negativ");
            }
            if (latura4 > 100) {  //sa fie mai mic decat 100

                latura4Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura4.isEmpty()) {
                latura4Ecran.setText("");
            } else {
                latura4Ecran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }
    }//GEN-LAST:event_latura4EcranFocusLost

    private void creareVector() {

        Patrulater p0 = new Patrulater();
        Patrulater p1 = new Patrulater(-2, 3, 4, 2.5);
        Patrulater p2 = new Patrulater(2, 3, 4, 2.1);
        Patrulater p3 = new Patrulater(6, 9, 8, 3);
        vectPatr.add(p0);
        vectPatr.add(p1);
        vectPatr.add(p2);
        vectPatr.add(p3);

    }
    private void vectorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorListaActionPerformed
        // TODO add your handling code here:
        latura1Ecran.setText(""); //aici cele 4 casute ca sa se stearga datele precedente,sa fie gol
        latura2Ecran.setText("");
        latura3Ecran.setText("");
        latura4Ecran.setText("");

        ecranPerimetru.setText("");

        creareVector();
        String optiune = String.valueOf(vectorLista.getSelectedItem());  //pentru a alege din valorile prestabilite

        switch (optiune) {
            case "---------------------": {
                ecranAfisareTot.setText("");
                break;
            }
            case "Patrulater 1": {
                ecranAfisareTot.setText(vectPatr.get(0).toString());
                break;
            }
            case "Patrulater 2": {
                ecranAfisareTot.setText(vectPatr.get(1).toString());
                break;
            }
            case "Patrulater 3": {
                ecranAfisareTot.setText(vectPatr.get(2).toString());
                break;
            }
            case "Patrulater 4": {
                ecranAfisareTot.setText(vectPatr.get(3).toString());
                break;
            }
        }
    }//GEN-LAST:event_vectorListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPatrulater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPatrulater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPatrulater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPatrulater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPatrulater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonPerimetru;
    private javax.swing.JTextArea ecranAfisareTot;
    private javax.swing.JTextField ecranPerimetru;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latura1Ecran;
    private javax.swing.JTextField latura2Ecran;
    private javax.swing.JTextField latura3Ecran;
    private javax.swing.JTextField latura4Ecran;
    private javax.swing.JComboBox<String> vectorLista;
    // End of variables declaration//GEN-END:variables
}
