/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.util.ArrayList;

/**
 *
 * @author sorin
 */
public class GUIParalelogram extends javax.swing.JFrame {

    /**
     * Creates new form GUIParalelogram
     */
    public GUIParalelogram() {
        initComponents();
    }

    Paralelogram paralelogram = new Paralelogram();
    String mesajLatura1, mesajLatura2, mesajInaltime;
    double Latura1, Latura2, Inaltime;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        latura1Ecran = new javax.swing.JTextField();
        latura2Ecran = new javax.swing.JTextField();
        inaltimeEcran = new javax.swing.JTextField();
        ecranAfisarePerimetru = new javax.swing.JTextField();
        ecranAfisareArie = new javax.swing.JTextField();
        butonPerimetru = new javax.swing.JButton();
        butonArie = new javax.swing.JButton();
        butonAfisareTot = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAfisareTot = new javax.swing.JTextPane();
        vectorLista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setMinimumSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("Paralelogram");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 56, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel2.setText("Latura 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 184, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Latura 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 246, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel8.setText("Inaltime 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 308, -1, -1));

        latura1Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura1Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura1EcranFocusLost(evt);
            }
        });
        latura1Ecran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latura1EcranActionPerformed(evt);
            }
        });
        getContentPane().add(latura1Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 176, 150, 40));

        latura2Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura2Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura2EcranFocusLost(evt);
            }
        });
        getContentPane().add(latura2Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 238, 150, 40));

        inaltimeEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        inaltimeEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inaltimeEcranFocusLost(evt);
            }
        });
        getContentPane().add(inaltimeEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 300, 150, 40));

        ecranAfisarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        getContentPane().add(ecranAfisarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 386, 220, 38));

        ecranAfisareArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisareArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranAfisareArieActionPerformed(evt);
            }
        });
        getContentPane().add(ecranAfisareArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 470, 220, 38));

        butonPerimetru.setBackground(new java.awt.Color(204, 0, 0));
        butonPerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonPerimetru.setText("Perimetru");
        butonPerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonPerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 379, 144, 53));

        butonArie.setBackground(new java.awt.Color(204, 0, 0));
        butonArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonArie.setText("Arie");
        butonArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonArieActionPerformed(evt);
            }
        });
        getContentPane().add(butonArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 463, 144, 53));

        butonAfisareTot.setBackground(new java.awt.Color(204, 0, 0));
        butonAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonAfisareTot.setText("Mai multe");
        butonAfisareTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAfisareTotActionPerformed(evt);
            }
        });
        getContentPane().add(butonAfisareTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 568, 144, 53));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel5.setText("Exemple de paralelogram :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 200, 30));

        textAfisareTot.setBorder(null);
        textAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(textAfisareTot);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 553, 319, 100));

        vectorLista.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        vectorLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------", "Paralelogram 1", "Paralelogram 2", "Paralelogram 3", "Paralelogram 4" }));
        vectorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorListaActionPerformed(evt);
            }
        });
        getContentPane().add(vectorLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Loredana\\Desktop\\Test\\src\\Test\\resursePoze\\generic.jpg")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void latura1EcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latura1EcranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latura1EcranActionPerformed

    private void butonArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonArieActionPerformed
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();
        mesajLatura2 = latura2Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();

        try {                                            //se verifica daca sunt numere sau alte caractere
            Latura1 = Double.parseDouble(mesajLatura1);
            Latura2 = Double.parseDouble(mesajLatura2);
            Inaltime = Double.parseDouble(mesajInaltime);
            if (Latura1 > 0 && Latura2 > 0 && Inaltime > 0) {   //cazul favorit
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                paralelogram.setLatura1(Latura1);
                paralelogram.setLatura2(Latura2);
                paralelogram.setInaltime(Inaltime);
                paralelogram.calculeazaAria();

                double arie = paralelogram.getArie();

                System.out.println("Aria este " + arie);
                ecranAfisareArie.setText(Double.toString(arie));

            }

        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisareArie.setText("EROARE!Dim incorecte");
            System.out.println("EROARE!dimensiuni incorecte");
        }


    }//GEN-LAST:event_butonArieActionPerformed

    private void ecranAfisareArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranAfisareArieActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ecranAfisareArieActionPerformed

    private void butonPerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPerimetruActionPerformed
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();
        mesajLatura2 = latura2Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();

        try {                                             //se verifica daca sunt numere sau alte caractere
            Latura1 = Double.parseDouble(mesajLatura1);
            Latura2 = Double.parseDouble(mesajLatura2);
            Inaltime = Double.parseDouble(mesajInaltime);

            if (Latura1 > 0 && Latura2 > 0 && Inaltime > 0) {
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                paralelogram.setLatura1(Latura1);
                paralelogram.setLatura2(Latura2);
                paralelogram.setLatura3(Latura1);
                paralelogram.setLatura4(Latura2);
                paralelogram.setInaltime(Inaltime);

                double perim = paralelogram.calculPerimetru();

                System.out.println("Perimetrul este " + perim);
                ecranAfisarePerimetru.setText(Double.toString(perim));

            }
        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisarePerimetru.setText("EROARE!Dim incorecte");
            System.out.println("EROARE!Dimensiuni incorecte");
        }

    }//GEN-LAST:event_butonPerimetruActionPerformed

    private void butonAfisareTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAfisareTotActionPerformed
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();
        mesajLatura2 = latura2Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();
        try {
            Latura1 = Double.parseDouble(mesajLatura1);              //daca laturile citite sunt numere 
            Latura2 = Double.parseDouble(mesajLatura2);
            Inaltime = Double.parseDouble(mesajInaltime);

            if (Latura1 > 0 && Latura2 > 0 && Inaltime > 0) {

                textAfisareTot.setText(paralelogram.toString());

            }

        } catch (Exception e) {   //daca nu sunt numere 
            textAfisareTot.setText("");   //astfel se goleste casuta cu "MAI MULTE"
            textAfisareTot.setEnabled(false);   //ea nu va mai putea fi editabila,deci nu va mai aparea nimic,dezactivata

        }

    }//GEN-LAST:event_butonAfisareTotActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GUImain meniu = new GUImain();  //aici cand se inchide fereasra,sa se deschida meniul initial
        meniu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void latura1EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura1EcranFocusLost
        // TODO add your handling code here:
        mesajLatura1 = latura1Ecran.getText();    //citire mesaj de la casuta latura1
        try {
            Latura1 = Double.parseDouble(mesajLatura1); //daca este numar sau nu
            if (Latura1 < 0) {

                latura1Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");

            }
            if (Latura1 > 100) {
                latura1Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura1.isEmpty()) {
                latura1Ecran.setText("");
            } else {
                latura1Ecran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_latura1EcranFocusLost

    private void latura2EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura2EcranFocusLost
        // TODO add your handling code here:
        mesajLatura2 = latura2Ecran.getText();    //citire mesaj de la casuta latura1
        try {
            Latura2 = Double.parseDouble(mesajLatura2); //daca este numar sau nu
            if (Latura2 < 0) {

                latura2Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE!Negativ");

            }
            if (Latura2 > 100) {
                latura2Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura2.isEmpty()) {
                latura2Ecran.setText("");
            } else {
                latura2Ecran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_latura2EcranFocusLost

    private void inaltimeEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inaltimeEcranFocusLost
        // TODO add your handling code here:
        mesajInaltime = inaltimeEcran.getText();    //citire mesaj de la casuta latura1
        try {
            Inaltime = Double.parseDouble(mesajInaltime); //daca este numar sau nu
            if (Inaltime < 0) {

                inaltimeEcran.setText("EROARE! Negativ");
                System.out.println("EROARE!Negativ");

            }
            if (Inaltime > 100) {
                inaltimeEcran.setText("EROARE! Depasit");
                System.out.println("EROARE!depasit");
            }

        } catch (NumberFormatException e) {
            if (mesajInaltime.isEmpty()) {
                inaltimeEcran.setText("");
            } else {
                inaltimeEcran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_inaltimeEcranFocusLost

    private void vectorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorListaActionPerformed
        // TODO add your handling code here:
        latura1Ecran.setText("");        //aici cele 4 casute ca sa se stearga datele precedente,sa fie gol
        latura2Ecran.setText("");
        inaltimeEcran.setText("");
        ecranAfisarePerimetru.setText("");
        ecranAfisareArie.setText("");
        textAfisareTot.setEnabled(true);

        Paralelogram p1 = new Paralelogram();
        Paralelogram p2 = new Paralelogram(3.0, 4.0, 5.0, 70);
        Paralelogram p3 = new Paralelogram(2, 7, 5, 120);
        Paralelogram p4 = new Paralelogram(6, 8, 5, 85);

        ArrayList<Paralelogram> vectPat = new ArrayList<Paralelogram>();  //am creat un vector care nu are o limita de elemente impusa
        vectPat.add(p1);
        vectPat.add(p2);
        vectPat.add(p3);
        vectPat.add(p4);

        String optiune = String.valueOf(vectorLista.getSelectedItem());  //pentru a alege din valorile prestabilite

        switch (optiune) {
            case "--------------------": {
                textAfisareTot.setText("");
                break;
            }
            case "Paralelogram 1": {
                textAfisareTot.setText(vectPat.get(0).toString());
                break;
            }
            case "Paralelogram 2": {
                textAfisareTot.setText(vectPat.get(1).toString());
                break;
            }
            case "Paralelogram 3": {
                textAfisareTot.setText(vectPat.get(2).toString());
                break;
            }
            case "Paralelogram 4": {
                textAfisareTot.setText(vectPat.get(3).toString());
                break;
            }

        }
    }//GEN-LAST:event_vectorListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIParalelogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIParalelogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIParalelogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIParalelogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIParalelogram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAfisareTot;
    private javax.swing.JButton butonArie;
    private javax.swing.JButton butonPerimetru;
    private javax.swing.JTextField ecranAfisareArie;
    private javax.swing.JTextField ecranAfisarePerimetru;
    private javax.swing.JTextField inaltimeEcran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latura1Ecran;
    private javax.swing.JTextField latura2Ecran;
    private javax.swing.JTextPane textAfisareTot;
    private javax.swing.JComboBox<String> vectorLista;
    // End of variables declaration//GEN-END:variables
}
