/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.util.ArrayList;

/**
 *
 * @author Loredana
 */
public class GUIPatrat extends javax.swing.JFrame {

    /**
     * Creates new form GUIPatrat
     */
    public GUIPatrat() {
        initComponents();
    }

    Patrat patrat = new Patrat();
    String mesajLatura;
    double latura;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaturaEcran = new javax.swing.JTextField();
        ecranAfisarePerimetru = new javax.swing.JTextField();
        ecranAfisareArie = new javax.swing.JTextField();
        latura1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        butonArie = new javax.swing.JButton();
        butonPerimetru = new javax.swing.JButton();
        butonMaiMulte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vectorLista = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAfisareTot = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setMinimumSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LaturaEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        LaturaEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LaturaEcranFocusLost(evt);
            }
        });
        getContentPane().add(LaturaEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 184, 190, 34));

        ecranAfisarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisarePerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranAfisarePerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(ecranAfisarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 282, 190, 39));

        ecranAfisareArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        getContentPane().add(ecranAfisareArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 383, 190, 39));

        latura1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        latura1.setText("    Latura");
        latura1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(latura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 184, 140, 34));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setText("Pătrat");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 59, 104, 58));

        butonArie.setBackground(new java.awt.Color(204, 0, 0));
        butonArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonArie.setText("Arie");
        butonArie.setMaximumSize(new java.awt.Dimension(119, 31));
        butonArie.setMinimumSize(new java.awt.Dimension(119, 31));
        butonArie.setPreferredSize(new java.awt.Dimension(119, 31));
        butonArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonArieActionPerformed(evt);
            }
        });
        getContentPane().add(butonArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 368, 139, 54));

        butonPerimetru.setBackground(new java.awt.Color(204, 0, 0));
        butonPerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonPerimetru.setText("Perimetru");
        butonPerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonPerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 271, 139, 54));

        butonMaiMulte.setBackground(new java.awt.Color(204, 0, 0));
        butonMaiMulte.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonMaiMulte.setText("Mai multe");
        butonMaiMulte.setMaximumSize(new java.awt.Dimension(119, 31));
        butonMaiMulte.setMinimumSize(new java.awt.Dimension(119, 31));
        butonMaiMulte.setPreferredSize(new java.awt.Dimension(119, 31));
        butonMaiMulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonMaiMulteActionPerformed(evt);
            }
        });
        getContentPane().add(butonMaiMulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 502, 139, 54));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel2.setText("Exemple patrate:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, 20));

        vectorLista.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        vectorLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------", "Patrat 1", "Patrat 2", "Patrat 3", "Patrat 4" }));
        vectorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorListaActionPerformed(evt);
            }
        });
        getContentPane().add(vectorLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, 30));

        textAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        textAfisareTot.setMinimumSize(new java.awt.Dimension(10, 10));
        jScrollPane2.setViewportView(textAfisareTot);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 477, 361, 88));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Loredana\\Desktop\\Test\\src\\Test\\resursePoze\\generic.jpg")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonPerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPerimetruActionPerformed
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();   //se extrag stringurile citite in casuta alba
        try {
            latura = Double.parseDouble(mesajLatura);     //converteste din string in double
            if (latura > 0) {
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                patrat.setLatura(latura);

                double perimetru = patrat.calculPerimetru();
                patrat.calculDiagonala();

                System.out.println("Perimetrul este " + perimetru);
                ecranAfisarePerimetru.setText(Double.toString(perimetru));
            
            }

        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisarePerimetru.setText("EROARE! Dim incorecta");
            System.out.println("EROARE! Dimensiune incorecta");
        }

    }//GEN-LAST:event_butonPerimetruActionPerformed

    private void ecranAfisarePerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranAfisarePerimetruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecranAfisarePerimetruActionPerformed

    private void butonArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonArieActionPerformed
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();   //se extrag stringurile citite in casuta alba
        try {
            latura = Double.parseDouble(mesajLatura);   //conversie din string in double pt lungime
            if (latura > 0) {
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                patrat.setLatura(latura);

                patrat.calculArie();
                double arie = patrat.getArie();

                System.out.println("Aria este " + arie);
                ecranAfisareArie.setText(Double.toString(arie));
            } 

        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisareArie.setText("EROARE! Dim incorecta");
            System.out.println("EROARE! Dimensiune incorecta");
        }

    }//GEN-LAST:event_butonArieActionPerformed

    private void butonMaiMulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonMaiMulteActionPerformed
        // TODO add your handling code here:
        try {
            latura = Double.parseDouble(mesajLatura);   //conversie din string in double pt lungime
            if (latura > 0) {
                textAfisareTot.setText(patrat.toString());
            } 

        } catch (NumberFormatException e) {   //daca nu sunt numere 
            textAfisareTot.setText("");   //astfel se goleste casuta cu "MAI MULTE"
            textAfisareTot.setEnabled(false);   //ea nu va mai putea fi editabila,deci nu va mai aparea nimic,dezactivata
        }
    }//GEN-LAST:event_butonMaiMulteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GUImain meniu = new GUImain();  //aici cand se inchide fereasra,sa se deschida meniul initial
        meniu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void LaturaEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LaturaEcranFocusLost
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();
        try {
            latura = Double.parseDouble(mesajLatura); //daca este numar sau nu
            if (latura < 0) {

                LaturaEcran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");

            }
            if (latura > 100) {
                LaturaEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura.isEmpty()) {
                LaturaEcran.setText("");
            } else {
                LaturaEcran.setText("EROARE! Nan");
                System.out.println("EROARE! Nan");
            }
        }

    }//GEN-LAST:event_LaturaEcranFocusLost

    private void vectorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorListaActionPerformed
        // TODO add your handling code here:
        LaturaEcran.setText("");        //aici cele 3 casute ca sa se stearga datele precedente,sa fie gol
        ecranAfisarePerimetru.setText("");
        ecranAfisareArie.setText("");
        textAfisareTot.setEnabled(true);
        Patrat pt1, pt2, pt3, pt4;
        pt1 = new Patrat();
        pt2 = new Patrat(7);
        pt3 = new Patrat(3);
        pt4 = new Patrat(5);

        ArrayList<Patrat> vectP = new ArrayList<Patrat>();  //am creat un vector care nu are o limita de elemente impusa
        vectP.add(pt1);
        vectP.add(pt2);
        vectP.add(pt3);
        vectP.add(pt4);

        String optiune = String.valueOf(vectorLista.getSelectedItem());  //pentru a alege din valorile prestabilite

        switch (optiune) {
            case "-----------------": {
                textAfisareTot.setText("");
                break;
            }
            case "Patrat 1": {
                textAfisareTot.setText(vectP.get(0).toString());
                break;
            }
            case "Patrat 2": {
                textAfisareTot.setText(vectP.get(1).toString());
                break;
            }
            case "Patrat 3": {
                textAfisareTot.setText(vectP.get(2).toString());
                break;
            }
            case "Patrat 4": {
                textAfisareTot.setText(vectP.get(3).toString());
                break;
            }

        }
    }//GEN-LAST:event_vectorListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPatrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPatrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPatrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPatrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPatrat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LaturaEcran;
    private javax.swing.JButton butonArie;
    private javax.swing.JButton butonMaiMulte;
    private javax.swing.JButton butonPerimetru;
    private javax.swing.JTextField ecranAfisareArie;
    private javax.swing.JTextField ecranAfisarePerimetru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel latura1;
    private javax.swing.JTextPane textAfisareTot;
    private javax.swing.JComboBox<String> vectorLista;
    // End of variables declaration//GEN-END:variables
}
