package Test;

import java.util.ArrayList;

public class GUIRomb extends javax.swing.JFrame {

    /**
     * Creates new form GUIRomb
     */
    public GUIRomb() {
        initComponents();
    }
    private Romb r = new Romb();
    String mesajLatura, mesajMasuraU;
    double latura, masuraU;
    ArrayList<Romb> vectR = new ArrayList<Romb>();  //am creat un vector care nu are o limita de elemente impusa

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LaturaEcran = new javax.swing.JTextField();
        MasuraUnghiEcran = new javax.swing.JTextField();
        ecranAfisarePerimetru = new javax.swing.JTextField();
        ecranAfisareArie = new javax.swing.JTextField();
        butonAfisarePerimetru = new javax.swing.JButton();
        butonAfisareArie = new javax.swing.JButton();
        butonMaiMulte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAfisareTot = new javax.swing.JTextPane();
        Exemple = new javax.swing.JLabel();
        vectorlista = new javax.swing.JComboBox<>();
        butonCelMaiMarePerimetru = new javax.swing.JButton();
        ecranMaxim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setText("Romb");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 99, 66));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel2.setText("Latura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 221, 126, 32));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Masura Unghi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 284, -1, 32));

        LaturaEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        LaturaEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LaturaEcranFocusLost(evt);
            }
        });
        getContentPane().add(LaturaEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 222, 126, 32));

        MasuraUnghiEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        MasuraUnghiEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MasuraUnghiEcranFocusLost(evt);
            }
        });
        getContentPane().add(MasuraUnghiEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 284, 126, 32));

        ecranAfisarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisarePerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranAfisarePerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(ecranAfisarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 374, 230, 30));

        ecranAfisareArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisareArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranAfisareArieActionPerformed(evt);
            }
        });
        getContentPane().add(ecranAfisareArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 464, 230, 30));

        butonAfisarePerimetru.setBackground(new java.awt.Color(204, 0, 0));
        butonAfisarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonAfisarePerimetru.setText("Perimetru");
        butonAfisarePerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAfisarePerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonAfisarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 366, 130, 45));

        butonAfisareArie.setBackground(new java.awt.Color(204, 0, 0));
        butonAfisareArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonAfisareArie.setText("Arie");
        butonAfisareArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAfisareArieActionPerformed(evt);
            }
        });
        getContentPane().add(butonAfisareArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 458, 130, 45));

        butonMaiMulte.setBackground(new java.awt.Color(204, 0, 0));
        butonMaiMulte.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonMaiMulte.setText("Mai multe");
        butonMaiMulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonMaiMulteActionPerformed(evt);
            }
        });
        getContentPane().add(butonMaiMulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 550, 130, 45));

        textAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(textAfisareTot);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 529, 307, 100));

        Exemple.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Exemple.setText("Exemple Romburi:");
        getContentPane().add(Exemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 130, 30));

        vectorlista.setFont(new java.awt.Font("Bookman Old Style", 0, 13)); // NOI18N
        vectorlista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------", "Romb 1", "Romb 2", "Romb 3", "Romb 4" }));
        vectorlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorlistaActionPerformed(evt);
            }
        });
        getContentPane().add(vectorlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 160, 30));

        butonCelMaiMarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        butonCelMaiMarePerimetru.setText("Cel mai mare perimetru");
        butonCelMaiMarePerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCelMaiMarePerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonCelMaiMarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 233, 180, 30));

        ecranMaxim.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        getContentPane().add(ecranMaxim, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 234, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Loredana\\Desktop\\Test\\src\\Test\\resursePoze\\generic.jpg")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creareVector() {
        Romb r1 = new Romb();
        Romb r2 = new Romb(10.0, 3);
        Romb r3 = new Romb(6, 8);
        Romb r4 = new Romb(20, 45);

        vectR.add(r1);
        vectR.add(r2);
        vectR.add(r3);
        vectR.add(r4);
    }

    private void butonAfisarePerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAfisarePerimetruActionPerformed
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();
        mesajMasuraU = MasuraUnghiEcran.getText();

        try {                                             //se verifica daca sunt numere sau alte caractere
            latura = Double.parseDouble(mesajLatura);
            masuraU = Double.parseDouble(mesajMasuraU);
            if (latura > 0 && masuraU > 0) {
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                r.setLatura(latura);
                r.setMasuraUnghi(masuraU);

                double perim = r.calculPerimetru();

                System.out.println("Perimetrul este " + perim);
                ecranAfisarePerimetru.setText(Double.toString(perim));
            }
        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisarePerimetru.setText("EROARE! Dim incorecte");
            System.out.println("EROARE!dimensiuni incorecte");
        }

    }//GEN-LAST:event_butonAfisarePerimetruActionPerformed

    private void ecranAfisarePerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranAfisarePerimetruActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_ecranAfisarePerimetruActionPerformed

    private void butonMaiMulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonMaiMulteActionPerformed
        // TODO add your handling code here:

        textAfisareTot.setText(r.toString());
        try {
            latura = Double.parseDouble(mesajLatura);              //daca laturile citite sunt numere 
            masuraU = Double.parseDouble(mesajMasuraU);
            if (latura > 0 && masuraU > 0) {

                textAfisareTot.setText(r.toString());
            }

        } catch (Exception e) {   //daca nu sunt numere 
            textAfisareTot.setText("");//astfel se goleste casuta cu "MAI MULTE"
        }
    }//GEN-LAST:event_butonMaiMulteActionPerformed

    private void butonAfisareArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAfisareArieActionPerformed
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();   //se extrag stringurile citite in casuta alba
        mesajMasuraU = MasuraUnghiEcran.getText();

        try {                                            //se verifica daca sunt numere sau alte caractere
            latura = Double.parseDouble(mesajLatura);
            masuraU = Double.parseDouble(mesajMasuraU);
            if (latura > 0 && masuraU > 0) {   //cazul favorit
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                r.setLatura(latura);
                r.setMasuraUnghi(masuraU);

                r.calculArie();
                double arie = r.getArie();

                System.out.println("Aria este " + arie);
                ecranAfisareArie.setText(Double.toString(arie));
                if (r.getArie() < 0) {
                    ecranAfisareArie.setText("Arie negativa!");
                    System.out.println("EROARE! Arie negativa!");
                }

            }

        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisareArie.setText("EROARE! Dim incorecte");
            System.out.println("EROARE!Dimensiuni incorecte");
        }


    }//GEN-LAST:event_butonAfisareArieActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GUImain meniu = new GUImain();  //aici cand se inchide fereasra,sa se deschida meniul initial
        meniu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void ecranAfisareArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranAfisareArieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecranAfisareArieActionPerformed


    private void vectorlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorlistaActionPerformed
        // TODO add your handling code here:
        LaturaEcran.setText("");        //aici cele 4 casute ca sa se stearga datele precedente,sa fie gol
        MasuraUnghiEcran.setText("");
        ecranAfisarePerimetru.setText("");
        ecranAfisareArie.setText("");
        textAfisareTot.setEnabled(true);

        creareVector();
        String optiune = String.valueOf(vectorlista.getSelectedItem());  //converteste alegerea facuta

        switch (optiune) {
            case "----------------------": {
                textAfisareTot.setText("");
                break;
            }
            case "Romb 1": {
                textAfisareTot.setText(vectR.get(0).toString());
                break;
            }
            case "Romb 2": {
                textAfisareTot.setText(vectR.get(1).toString());
                break;
            }
            case "Romb 3": {
                textAfisareTot.setText(vectR.get(2).toString());
                break;
            }
            case "Romb 4": {
                textAfisareTot.setText(vectR.get(3).toString());
                break;
            }
        }
    }//GEN-LAST:event_vectorlistaActionPerformed

    private void LaturaEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LaturaEcranFocusLost
        // TODO add your handling code here:
        mesajLatura = LaturaEcran.getText();
        try {
            latura = Double.parseDouble(mesajLatura);
            if (latura <= 0) {
                LaturaEcran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");
            }
            if (latura > 100) {  //sa fie mai mic decat 100

                LaturaEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura.isEmpty()) {
                LaturaEcran.setText("");
            } else {

                LaturaEcran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }
    }//GEN-LAST:event_LaturaEcranFocusLost

    private void MasuraUnghiEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MasuraUnghiEcranFocusLost
        // TODO add your handling code here:
        mesajMasuraU = MasuraUnghiEcran.getText();
        try {
            masuraU = Double.parseDouble(mesajMasuraU);
            if (masuraU <= 0) {
                MasuraUnghiEcran.setText("EROARE!Negativ");
                System.out.println("EROARE! Negativ");
            }
            if (masuraU > 100) {  //sa fie mai mic decat 100

                MasuraUnghiEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajMasuraU.isEmpty()) {
                MasuraUnghiEcran.setText("");
            } else {
                MasuraUnghiEcran.setText("EROARE!Nan");  //eroare not a number
                System.out.println("EROARE!Nan");
            }  //afisare in linie de comanda
        }

    }//GEN-LAST:event_MasuraUnghiEcranFocusLost

    private void butonCelMaiMarePerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCelMaiMarePerimetruActionPerformed
        // TODO add your handling code here:
        creareVector();
        double maxim;
        maxim = vectR.get(0).getPerimetru();
        for (int i = 1; i < vectR.size(); i++) {
            if (vectR.get(i).getPerimetru() > maxim) {
                maxim = vectR.get(i).getPerimetru();
            }
        }

        ecranMaxim.setText(Double.toString(maxim));
    }//GEN-LAST:event_butonCelMaiMarePerimetruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRomb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exemple;
    private javax.swing.JTextField LaturaEcran;
    private javax.swing.JTextField MasuraUnghiEcran;
    private javax.swing.JButton butonAfisareArie;
    private javax.swing.JButton butonAfisarePerimetru;
    private javax.swing.JButton butonCelMaiMarePerimetru;
    private javax.swing.JButton butonMaiMulte;
    private javax.swing.JTextField ecranAfisareArie;
    private javax.swing.JTextField ecranAfisarePerimetru;
    private javax.swing.JTextField ecranMaxim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textAfisareTot;
    private javax.swing.JComboBox<String> vectorlista;
    // End of variables declaration//GEN-END:variables

}
