/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.util.ArrayList;

/**
 *
 * @author sorin
 */
public class GUITrapez extends javax.swing.JFrame {

    /**
     * Creates new form GUITrapez
     */
    public GUITrapez() {
        initComponents();
    }

    Trapez trapez = new Trapez();
    String mesajBazaMica, mesajBazaMare, mesajLatura3, mesajLatura4, mesajInaltime;
    double bazaMica, bazaMare, Latura3, Latura4, inaltime;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bazaMicaEcran = new javax.swing.JTextField();
        bazaMareEcran = new javax.swing.JTextField();
        latura3Ecran = new javax.swing.JTextField();
        latura4Ecran = new javax.swing.JTextField();
        ecranAfisarePerimetru = new javax.swing.JTextField();
        ecranAfisareArie = new javax.swing.JTextField();
        inaltimeEcran = new javax.swing.JTextField();
        butonPerimetru = new javax.swing.JButton();
        butonMaiMulte = new javax.swing.JButton();
        butonArie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAfisareTot = new javax.swing.JTextPane();
        vectorLista = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setText("   Trapez");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 155, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Baza mica");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 157, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel4.setText("Baza mare");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 204, 135, -1));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel5.setText("Latura 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 298, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel6.setText("Latura 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 345, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel9.setText("Inaltime");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 251, -1, -1));

        bazaMicaEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        bazaMicaEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bazaMicaEcranFocusLost(evt);
            }
        });
        bazaMicaEcran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaMicaEcranActionPerformed(evt);
            }
        });
        getContentPane().add(bazaMicaEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 151, 170, -1));

        bazaMareEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        bazaMareEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bazaMareEcranFocusLost(evt);
            }
        });
        bazaMareEcran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaMareEcranActionPerformed(evt);
            }
        });
        getContentPane().add(bazaMareEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 201, 170, -1));

        latura3Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura3Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura3EcranFocusLost(evt);
            }
        });
        latura3Ecran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latura3EcranActionPerformed(evt);
            }
        });
        getContentPane().add(latura3Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 301, 170, -1));

        latura4Ecran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        latura4Ecran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                latura4EcranFocusLost(evt);
            }
        });
        latura4Ecran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latura4EcranEcranActionPerformed(evt);
            }
        });
        getContentPane().add(latura4Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 351, 170, -1));

        ecranAfisarePerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        ecranAfisarePerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranAfisarePerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(ecranAfisarePerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 431, 230, 36));

        ecranAfisareArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        getContentPane().add(ecranAfisareArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 511, 230, 36));

        inaltimeEcran.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        inaltimeEcran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inaltimeEcranFocusLost(evt);
            }
        });
        getContentPane().add(inaltimeEcran, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 251, 170, -1));

        butonPerimetru.setBackground(new java.awt.Color(204, 0, 0));
        butonPerimetru.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonPerimetru.setText("Perimetru");
        butonPerimetru.setPreferredSize(new java.awt.Dimension(67, 31));
        butonPerimetru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPerimetruActionPerformed(evt);
            }
        });
        getContentPane().add(butonPerimetru, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 420, 127, 50));

        butonMaiMulte.setBackground(new java.awt.Color(204, 0, 0));
        butonMaiMulte.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonMaiMulte.setText("Mai multe");
        butonMaiMulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonMaiMulteActionPerformed(evt);
            }
        });
        getContentPane().add(butonMaiMulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 594, 127, 50));

        butonArie.setBackground(new java.awt.Color(204, 0, 0));
        butonArie.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        butonArie.setText("Arie");
        butonArie.setBorderPainted(false);
        butonArie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonArieActionPerformed(evt);
            }
        });
        getContentPane().add(butonArie, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 504, 127, 50));

        textAfisareTot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(textAfisareTot);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 571, 316, 90));

        vectorLista.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        vectorLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------", "Trapez 1", "Trapez 2", "Trapez 3", "Trapez 4", " " }));
        vectorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorListaActionPerformed(evt);
            }
        });
        getContentPane().add(vectorLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 171, 155, 34));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel7.setText("Exemple trapezuri :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 129, 138, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Loredana\\Desktop\\Test\\src\\Test\\resursePoze\\generic.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void butonPerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPerimetruActionPerformed
        // TODO add your handling code here:
        mesajBazaMare = bazaMareEcran.getText();
        mesajBazaMica = bazaMicaEcran.getText();
        mesajLatura3 = latura3Ecran.getText();
        mesajLatura4 = latura4Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();

        try {                                             //se verifica daca sunt numere sau alte caractere
            bazaMica = Double.parseDouble(mesajBazaMica);
            bazaMare = Double.parseDouble(mesajBazaMare);
            Latura3 = Double.parseDouble(mesajLatura3);
            Latura4 = Double.parseDouble(mesajLatura4);
            inaltime = Double.parseDouble(mesajInaltime);
            if (bazaMica >= 0 && bazaMare >= 0 && Latura3 >= 0 && Latura4 >= 0 && inaltime >= 0) {
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                trapez.setLatura1(bazaMica);
                trapez.setLatura2(bazaMare);
                trapez.setLatura3(Latura3);
                trapez.setLatura4(Latura4);
                trapez.setInaltime(inaltime);

                double perim = trapez.calculPerimetru();
                System.out.println("Perimetrul este: " + perim);
                ecranAfisarePerimetru.setText(Double.toString(perim));
            }
        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisarePerimetru.setText("EROARE!Dim incorecte!");
            System.out.println("EROARE!Dim incorecte!");
        }
    }//GEN-LAST:event_butonPerimetruActionPerformed

    private void latura3EcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latura3EcranActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_latura3EcranActionPerformed

    private void bazaMareEcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaMareEcranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bazaMareEcranActionPerformed

    private void bazaMicaEcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaMicaEcranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bazaMicaEcranActionPerformed

    private void latura4EcranEcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latura4EcranEcranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latura4EcranEcranActionPerformed

    private void ecranAfisarePerimetruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranAfisarePerimetruActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ecranAfisarePerimetruActionPerformed

    private void butonArieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonArieActionPerformed
        // TODO add your handling code here:
        mesajBazaMare = bazaMareEcran.getText();
        mesajBazaMica = bazaMicaEcran.getText();
        mesajLatura3 = latura3Ecran.getText();
        mesajLatura4 = latura4Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();

        try {                                            //se verifica daca sunt numere sau alte caractere
            bazaMica = Double.parseDouble(mesajBazaMica);
            bazaMare = Double.parseDouble(mesajBazaMare);
            Latura3 = Double.parseDouble(mesajLatura3);
            Latura4 = Double.parseDouble(mesajLatura4);
            inaltime = Double.parseDouble(mesajInaltime);
            if (bazaMica >= 0 && bazaMare >= 0 && Latura3 >= 0 && Latura4 >= 0 && inaltime >= 0) {   //cazul favorit
                if (textAfisareTot.isEnabled() == false) {  //daca este dezactivata casuta de "mai multe"
                    textAfisareTot.setEnabled(true);   //se activeaza din nou
                }
                trapez.setLatura1(bazaMica);
                trapez.setLatura2(bazaMare);
                trapez.setLatura3(Latura3);
                trapez.setLatura4(Latura4);
                trapez.setInaltime(inaltime);

                trapez.calculeazaAria();
                double arie = trapez.getArie();

                System.out.println("Aria este " + arie);
                ecranAfisareArie.setText(Double.toString(arie));

            }

        } catch (Exception e) { //alte erori,mai ales cele in care nu estenumar,ci este altceva cee ce se citeste de la diemnsiuni

            ecranAfisareArie.setText("EROARE!Dim incorecte!");
            System.out.println("EROARE!Dimensiuni incorecte!");
        }
    }//GEN-LAST:event_butonArieActionPerformed

    private void butonMaiMulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonMaiMulteActionPerformed
        // TODO add your handling code here:
        mesajBazaMare = bazaMareEcran.getText();
        mesajBazaMica = bazaMicaEcran.getText();
        mesajLatura3 = latura3Ecran.getText();
        mesajLatura4 = latura4Ecran.getText();
        mesajInaltime = inaltimeEcran.getText();
        try {
            bazaMica = Double.parseDouble(mesajBazaMica);              //daca laturile citite sunt numere 
            bazaMare = Double.parseDouble(mesajBazaMare);
            Latura3 = Double.parseDouble(mesajLatura3);              //daca laturile citite sunt numere 
            Latura4 = Double.parseDouble(mesajLatura4);
            inaltime = Double.parseDouble(mesajInaltime);

            if (bazaMica >= 0 && bazaMare >= 0 && Latura3 >= 0 && Latura4 >= 0 && inaltime >= 0) {

                textAfisareTot.setText(trapez.toString());
            } else if (bazaMica < 0 || bazaMare < 0 || Latura3 < 0 || Latura4 < 0 || inaltime < 0) {   //daca sunt negative laturile
                textAfisareTot.setText("");
                textAfisareTot.setEnabled(false);
            }

        } catch (Exception e) {   //daca nu sunt numere 
            textAfisareTot.setText("");   //astfel se goleste casuta cu "MAI MULTE"
            textAfisareTot.setEnabled(false);   //ea nu va mai putea fi editabila,deci nu va mai aparea nimic,dezactivata

        }
    }//GEN-LAST:event_butonMaiMulteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GUImain meniu = new GUImain();  //aici cand se inchide fereasra,sa se deschida meniul initial
        meniu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void bazaMicaEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bazaMicaEcranFocusLost
        // TODO add your handling code here:
        mesajBazaMica = bazaMicaEcran.getText();    //citire mesaj de la casuta latura1
        try {
            bazaMica = Double.parseDouble(mesajBazaMica); //daca este numar sau nu
            if (bazaMica < 0) {

                bazaMicaEcran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");

            }
            if (bazaMica > 100) {
                bazaMicaEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajBazaMica.isEmpty()) {
                bazaMicaEcran.setText("");
            } else {
                bazaMicaEcran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }

    }//GEN-LAST:event_bazaMicaEcranFocusLost

    private void bazaMareEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bazaMareEcranFocusLost
        // TODO add your handling code here:
        mesajBazaMare = bazaMareEcran.getText();    //citire mesaj de la casuta latura1
        try {
            bazaMare = Double.parseDouble(mesajBazaMare); //daca este numar sau nu
            if (bazaMare < 0) {

                bazaMareEcran.setText("EROARE! Negativ");
                System.out.println("EROARE!Negativ");

            }
            if (bazaMare > 100) {
                bazaMareEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajBazaMare.isEmpty()) {
                bazaMareEcran.setText("");
            } else {
                bazaMareEcran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_bazaMareEcranFocusLost

    private void inaltimeEcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inaltimeEcranFocusLost
        // TODO add your handling code here:
        mesajInaltime = inaltimeEcran.getText();    //citire mesaj de la casuta latura1
        try {
            inaltime = Double.parseDouble(mesajInaltime); //daca este numar sau nu
            if (inaltime < 0) {

                inaltimeEcran.setText("EROARE! Negativ");
                System.out.println("EROARE!Negativ");

            }
            if (inaltime > 100) {
                inaltimeEcran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajInaltime.isEmpty()) {
                inaltimeEcran.setText("");
            } else {
                inaltimeEcran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_inaltimeEcranFocusLost

    private void latura3EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura3EcranFocusLost
        // TODO add your handling code here:
        mesajLatura3 = latura3Ecran.getText();    //citire mesaj de la casuta latura1
        try {
            Latura3 = Double.parseDouble(mesajLatura3); //daca este numar sau nu
            if (Latura3 < 0) {

                latura3Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");

            }
            if (Latura3 > 100) {
                latura3Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura3.isEmpty()) {
                latura3Ecran.setText("");
            } else {
                latura3Ecran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_latura3EcranFocusLost

    private void latura4EcranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_latura4EcranFocusLost
        // TODO add your handling code here:
        mesajLatura4 = latura4Ecran.getText();    //citire mesaj de la casuta latura1
        try {
            Latura4 = Double.parseDouble(mesajLatura4); //daca este numar sau nu
            if (Latura4 < 0) {

                latura4Ecran.setText("EROARE! Negativ");
                System.out.println("EROARE! Negativ");

            }
            if (Latura4 > 100) {
                latura4Ecran.setText("EROARE! Depasit");
            }
        } catch (NumberFormatException e) {
            if (mesajLatura4.isEmpty()) {
                latura4Ecran.setText("");
            } else {
                latura4Ecran.setText("EROARE!Nan");
                System.out.println("EROARE!Nan");
            }
        }
    }//GEN-LAST:event_latura4EcranFocusLost

    private void vectorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorListaActionPerformed
        // TODO add your handling code here:
        bazaMicaEcran.setText("");        //aici cele 4 casute ca sa se stearga datele precedente,sa fie gol
        bazaMareEcran.setText("");
        inaltimeEcran.setText("");
        latura3Ecran.setText("");
        latura4Ecran.setText("");
        ecranAfisarePerimetru.setText("");
        ecranAfisareArie.setText("");
        textAfisareTot.setEnabled(true);
        Trapez t1 = new Trapez();
        Trapez t2 = new Trapez(3.0, 4.0, 5.0, 3.0, 4.0);
        Trapez t3 = new Trapez(2, 7, 5, 4, 4);
        Trapez t4 = new Trapez(6, 8, 5, 6, 5);

        ArrayList<Trapez> vectTr = new ArrayList<Trapez>();  //am creat un vector care nu are o limita de elemente impusa
        vectTr.add(t1);
        vectTr.add(t2);
        vectTr.add(t3);
        vectTr.add(t4);

        String optiune = String.valueOf(vectorLista.getSelectedItem());  //pentru a alege din valorile prestabilite

        switch (optiune) {
            case "---------------": {
                textAfisareTot.setText("");
                break;
            }

            case "Trapez 1": {
                textAfisareTot.setText(vectTr.get(0).toString());
                break;
            }
            case "Trapez 2": {
                textAfisareTot.setText(vectTr.get(1).toString());
                break;
            }
            case "Trapez 3": {
                textAfisareTot.setText(vectTr.get(2).toString());
                break;
            }
            case "Trapez 4": {
                textAfisareTot.setText(vectTr.get(3).toString());
                break;
            }

        }
    }//GEN-LAST:event_vectorListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITrapez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITrapez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITrapez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITrapez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITrapez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bazaMareEcran;
    private javax.swing.JTextField bazaMicaEcran;
    private javax.swing.JButton butonArie;
    private javax.swing.JButton butonMaiMulte;
    private javax.swing.JButton butonPerimetru;
    private javax.swing.JTextField ecranAfisareArie;
    private javax.swing.JTextField ecranAfisarePerimetru;
    private javax.swing.JTextField inaltimeEcran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latura3Ecran;
    private javax.swing.JTextField latura4Ecran;
    private javax.swing.JTextPane textAfisareTot;
    private javax.swing.JComboBox<String> vectorLista;
    // End of variables declaration//GEN-END:variables
}
